### ISSUE TITLE
IP Whitelist

### ISSUE THREAD

**Issue by myavuzokumus** [TCPShield/RealIP#23]
Can you add ip whitelist settings to config?
Example:
```
ip-whitelist:
- 127.0.0.1
```

**Comment by kevinsal03** [comment]
I saw your issue after I just forked the project to add this in so I could use it with Geyser.

I **do not recommend using my version** unless you absolutely must make this work because it is just a bodge fix for now and may have some other unforeseen penalty that I did not notice. It has worked in my very minimal testing, and that is all I can speak to.

[Repo](https://github.com/kevinsal03/RealIP)
[Release](https://github.com/kevinsal03/RealIP/releases/tag/v2.3-FORK)

My apologies to the TCPShield team if you would rather me have not created this. I can take the repo down if you would prefer it not to exist until a proper implementation is done.

**Comment by hiksu** [comment]
Thank you so much @kevinsal03 for this! I would love to see a feature like this implemented into the main repo and mainly just commenting to show that this feature has demand.

**Comment by paulzhng** [comment]
Official implementation is being worked upon in https://github.com/TCPShield/RealIP/tree/ip-validation
Alpha build is available here: https://cloud.paul-zhang.de/s/KoQaWjcTZZkjx4H

Please keep in mind that this build isn't tested and hugely experimental yet. Custom CIDR entries can be added by creating a file in `/plugins/TCPShield/ip-whitelist/` and adding one CIDR entry (or plain IP) per line.

**Comment by kevinsal03** [comment]
@Fuzzlemann 
I'll install it on my dev server later today, and as long as it works I'll put it in production and report back later today.
I will also update my repo to push to the new branch.

**Comment by paulzhng** [comment]
Released with #24

**Comment by myavuzokumus** [comment]
```
Exception caught! java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick in phase STATUS with direction TO_CLIENT
```
After adding ip-whitelist support to the plugin, I tried it, but I started getting the following error. How can I solve it?

**Comment by paulzhng** [comment]
Which version of BungeeCord are you using?

**Comment by myavuzokumus** [comment]
I am using Aegis.
Version:
Aegis v8.8 GENJUTSU

**Comment by myavuzokumus** [comment]
When I add the IP address I get this problem, but other TCPShield forks for IP Whitelist feature  did not have such a problem.
