### ISSUE TITLE
RedisBungee Compatibility 

### ISSUE THREAD

**Issue by kolakz** [TCPShield/RealIP#45]
Hey, I would like to suggest redisbungee compatibility with TCPShield if you ever have the time!

**Comment by lhridder** [comment]
What functionality would you like to see that uses RedisBungee?

**Comment by kolakz** [comment]
Don't know too much about this so it might not be possible but maybe the ability to use TCPShield on my redis server?

**Comment by DylanKeir** [comment]
This should already be possible since we only validate hostnames and you can use a round robin proxy setup by adding multiple backends to your backend set in the TCPShield panel. If you have issues setting this up with TCPShield, please create a ticket at https://discord.gg/tcpshield and we'll help you get it sorted.
