### ISSUE TITLE
ProxyPingEvent error

### ISSUE THREAD

**Issue by Xemorr** [TCPShield/RealIP#87]
![image](https://user-images.githubusercontent.com/31805746/181782489-6521d285-7d21-4282-b175-352520f47d53.png)
Latest Velocity: Velocity 3.1.2-SNAPSHOT (git-6be344d9-b162)

**Comment by Astralchroma** [comment]
I can confirm this is an issue, my logs keep getting spammed with it.

**Comment by Alulom** [comment]
I have the same

**Comment by viper12358** [comment]
Can your players still log in? I've tested with this:
- TCPShield plugin 2.6.0
- Velocity 3.1.2-172
- Plugins: ViaBackward, ViaVersion, Geyser-Velocity
The errors did indeed show but I have no issue logging in.

Another test version I have is:
- TCPShield plugin 2.6.0
- Velocity 3.1.2-161
- Plugins: ViaBackward, ViaVersion, Geyser-Velocity
No errors were shown. You might need to downgrade your Velocity build or use `proxy-protocol` instead.

**Comment by Xemorr** [comment]
Yes. Velocity builds can't be downgraded at the moment, it is critical you stay on latest due to mojang's insane protocol changes re:chat

**Comment by viper12358** [comment]
Already made a note with our dev 2 days ago*. At the moment can you switch to proxy-protocol instead? Instructions can be found here:
https://docs.tcpshield.com/commonly-asked-questions

**Comment by authorless** [comment]
The documentation in TCPShield didn't help me... And when I turn on the proxy, I write constantly: "Disconnection"

**Comment by viper12358** [comment]
You have to do all of these steps:
- Remove TCPShield plugin (make sure the .jar is gone)
- Enable proxy-protocol (or haproxy-protocol if you are using Velocity) in your proxy's config. 
- Enable proxy-protocol in your backend set on the TCPShield Web panel.
And obviously direct login using IPv4 won't work because it's expecting **proxy connections**

**Comment by viper12358** [comment]
> The documentation in TCPShield didn't help me... And when I turn on the proxy, I write constantly: "Disconnection"

You have to do all of these steps:
- Remove TCPShield plugin (make sure the .jar is gone)
- Enable proxy-protocol (or haproxy-protocol if you are using Velocity) in your proxy's config.
- Enable proxy-protocol in your backend set on the TCPShield Web panel.

And obviously direct login using IPv4 won't work because it's expecting **proxy connections**

**Comment by DylanKeir** [comment]
@Xemorr I've looked through the errors here and you seem to be using a very old version of the plugin, could you come to Discord so we can assist you further? https://discord.gg/tcpshield

**Comment by DylanKeir** [comment]
Nevermind, I'm stupid. Fixed version here: https://github.com/TCPShield/RealIP/releases/tag/2.6.1
